# Generated by Django 3.2.16 on 2022-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('Ano', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ACno', models.CharField(max_length=10, serialize=False)),
                ('Acontent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=20)),
                ('Ccredit', models.DecimalField(decimal_places=0, max_digits=1)),
                ('CTno', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Gno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Sno', models.CharField(max_length=5, serialize=False)),
                ('Cno', models.CharField(max_length=10, serialize=False)),
                ('Gscore', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sno', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Spasswd', models.CharField(max_length=20)),
                ('Sname', models.CharField(max_length=20)),
                ('Sdept', models.CharField(max_length=20)),
                ('Stot_credit', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('Scredit', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('Savg', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Tno', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Tname', models.CharField(max_length=20)),
                ('Tdept', models.CharField(max_length=20)),
            ],
        ),
    ]
