# Generated by Django 4.1.4 on 2022-12-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="ACno",
        ),
        migrations.RemoveField(
            model_name="course",
            name="CTno",
        ),
        migrations.AddField(
            model_name="announcement",
            name="Cno",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.course",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="Tno",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="Cno",
            field=models.CharField(
                default="0",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="Cno",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.course",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="Gno",
            field=models.CharField(
                default="0",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="Gscore",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="grade",
            name="Sno",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="Sno",
            field=models.CharField(
                default="0",
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="Tno",
            field=models.CharField(
                default="0",
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
