# Generated by Django 4.1.4 on 2022-12-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_teacher_tpasswd"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="Cproperty",
            field=models.CharField(default="", max_length=20),
        ),
    ]
