# Generated by Django 4.1.4 on 2022-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_course_cproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="Glevel",
            field=models.CharField(default="E", max_length=1),
        ),
    ]
