# Generated by Django 4.1.4 on 2022-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_grade_glevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="Cnum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="Cpassnum",
            field=models.IntegerField(default=0),
        ),
    ]
