# Generated by Django 4.1.4 on 2022-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_course_cnum_course_cpassnum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="Cnum",
        ),
        migrations.RemoveField(
            model_name="course",
            name="Cpassnum",
        ),
        migrations.AddField(
            model_name="course",
            name="Cfail_ratio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
